# These are supported funding model platforms

github: #yashprakash13 # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
ko_fi: yashprakash13 # Replace with a single Ko-fi username
custom: 'paypal.me/yashprakash13' # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
